#
# This build script is provided by: https://github.com/svparijs/TravisCi.Example
# Author: Sebastiaan van Parijs
#
# For any issues of feedback report it at Github
#
# The TYPO3 project - inspiring people to share!
#

# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  - 5.5
  - hhvm

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql
  - DB=pgsql
  - FLOW_VERSION=2.3.*

# Setting up pre-requirements
before_script:
  - cd ..
  - git clone git://github.com/typo3-ci/TYPO3-Travis-Integration.git build-environment
  - source build-environment/install-helper.sh
  - mkdir Flow && curl -Lk https://gist.github.com/svparijs/5104c1700561f90421e1/raw/363b5db44acbb38ba81a233f2b6cdffcc849aede/Composer.json > Flow/composer.json
  # Symlink the package to the folder that its gonna go
  # [Replace Package key here]
  - mkdir -p Flow/Packages/Application && cd Flow/Packages/Application && ln -s ../../../TravisCi.Example && cd ../../
  # [Replace Package key here]

  - composer install --dev --verbose
  - if [[ "$DB" == "mysql" ]]; then mysql -u root -e 'create database flow;' && curl -Lk https://gist.github.com/raw/4276117/af19ef22064aae4875f41342845fb89de2f2b72c/Settings.Mysql.yaml > Configuration/Settings.yaml ; fi
  - if [[ "$DB" == "postgres" ]]; then psql -U postgres -c 'create database flow;' && curl -Lk https://gist.github.com/raw/4276117/40b5254f29e23ff3dcdf36ae72738ad71f9d9048/Settings.Postgresql.yaml > Configuration/Settings.yaml ; fi
  - mkdir Build/PhpUnit && curl -Lk https://gist.github.com/raw/4276117/950465122f99e9c1506495c50332891f2cb89f9d/FunctionalTests.xml > Build/PhpUnit/FunctionalTests.xml
  - curl -Lk https://gist.github.com/raw/4276117/af763946bd4fc7f0a0462952d71f68288a39c610/UnitTests.xml > Build/PhpUnit/UnitTests.xml

script:
  # Install Prerequirements
  - bin/phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml && bin/phpunit -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml
  # Code sniffer
  - bin/phpcs --extensions=php --standard=Packages/Libraries/typo3-qa/typo3flow/ruleset.xml	Packages/Application
  - if [[ "$DB" == "mysql" ]]; then ./flow doctrine:migrate --quiet && ./flow doctrine:migrate --version 0 --quiet ; fi
  - echo "Framework Tested."
  - bin/phpunit -c Build/PhpUnit/UnitTests.xml && bin/phpunit -c Build/PhpUnit/FunctionalTests.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  irc: "irc.freenode.org#refactory.it"